defaults: &defaults
  rotten_tomoatoes:
    key: ys5mave4hz6nw9d8ub6vac4u
  facebook:
   id: abcd1234
   secret: abcd1234

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults