defaults: &defaults
  rotten_tomoatoes:
    key: ys5mave4hz6nw9d8ub6vac4u
  facebook:
   id: ENV['FACEBOOK_ID']
   secret: ENV['FACEBOOK_SECRET']
  s3:
   access_key_id: AKIAJPLRKC2UNCXX2RSQ
   secret_access_key: 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
  google:
   api_key: AIzaSyBajsl8YcsJJr0F8ppBU3988GUdf0Ex4qM
  stripe:
    secret: sk_test_h7sjEuwspGRVUS3AsFwsM58x
    publishable: pk_test_7ObtQE0A3TITnUXi0weTYxZ1

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
  stripe:
    secret: sk_live_2hffJwDUq7UHpFjnw9h3WbYB
    publishable: pk_live_h2RDeUTxUvEQ57uiQTjNYR0p
