require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TaskTemplatesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # TaskTemplate. As you add validations to TaskTemplate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
        name: 'Task template',
        description: 'template description',
        required: true,
        schedule: "#{IceCube::Rule.daily.to_yaml}",
        rec_min_age: 2,
        rec_max_age: 8,
        def_min_age: 4,
        def_max_age: 6
    }
  }

  let(:invalid_attributes) {
    {
        name: nil
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TaskTemplatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  # TODO : Move these to the Admin test...
  # context "As an adminstrator" do
  #   before(:each) do
  #     @user = FactoryGirl.create(:user, admin: true)
  #     sign_in(@user)
  #   end
  #
  #   describe "GET index" do
  #     it "assigns all task_templates as @task_templates" do
  #       task_template = FactoryGirl.create(:task_template)
  #       get :index, {}, valid_session
  #       expect(assigns(:task_templates)).to match_array(TaskTemplate.all)
  #     end
  #   end
  #
  #   describe "GET show" do
  #     it "assigns the requested task_template as @task_template" do
  #       task_template = TaskTemplate.create! valid_attributes
  #       get :show, {:id => task_template.to_param}, valid_session
  #       expect(assigns(:task_template)).to eq(task_template)
  #     end
  #   end
  #
  #   describe "GET new" do
  #     it "assigns a new task_template as @task_template" do
  #       get :new, {}, valid_session
  #       expect(assigns(:task_template)).to be_a_new(TaskTemplate)
  #     end
  #   end
  #
  #   describe "GET edit" do
  #     it "assigns the requested task_template as @task_template" do
  #       task_template = TaskTemplate.create! valid_attributes
  #       get :edit, {:id => task_template.to_param}, valid_session
  #       expect(assigns(:task_template)).to eq(task_template)
  #     end
  #   end
  #
  #   describe "POST create" do
  #     describe "with valid params" do
  #       it "creates a new TaskTemplate" do
  #         expect {
  #           post :create, {:task_template => valid_attributes}, valid_session
  #         }.to change(TaskTemplate, :count).by(1)
  #       end
  #
  #       it "assigns a newly created task_template as @task_template" do
  #         post :create, {:task_template => valid_attributes}, valid_session
  #         expect(assigns(:task_template)).to be_a(TaskTemplate)
  #         expect(assigns(:task_template)).to be_persisted
  #       end
  #
  #       it "redirects to the index" do
  #         post :create, {:task_template => valid_attributes}, valid_session
  #         expect(response).to redirect_to(task_templates_path)
  #       end
  #     end
  #
  #     describe "with invalid params" do
  #       it "assigns a newly created but unsaved task_template as @task_template" do
  #         post :create, {:task_template => invalid_attributes}, valid_session
  #         expect(assigns(:task_template)).to be_a_new(TaskTemplate)
  #       end
  #
  #       it "re-renders the 'new' template" do
  #         post :create, {:task_template => invalid_attributes}, valid_session
  #         expect(response).to render_template("new")
  #       end
  #     end
  #   end
  #
  #   describe "PUT update" do
  #     describe "with valid params" do
  #       let(:new_attributes) {
  #         {
  #             name: 'New Name',
  #             description: 'Another description',
  #             required: false
  #         }
  #       }
  #
  #       it "updates the requested task_template" do
  #         task_template = TaskTemplate.create! valid_attributes
  #         put :update, {:id => task_template.to_param, :task_template => new_attributes}, valid_session
  #         task_template.reload
  #         expect(task_template.name).to eq("New Name")
  #         expect(task_template.description).to eq("Another description")
  #         expect(task_template.required).to be_falsey
  #
  #       end
  #
  #       it "assigns the requested task_template as @task_template" do
  #         task_template = TaskTemplate.create! valid_attributes
  #         put :update, {:id => task_template.to_param, :task_template => valid_attributes}, valid_session
  #         expect(assigns(:task_template)).to eq(task_template)
  #       end
  #
  #       it "redirects to the task_template index" do
  #         task_template = TaskTemplate.create! valid_attributes
  #         put :update, {:id => task_template.to_param, :task_template => valid_attributes}, valid_session
  #         expect(response).to redirect_to(task_templates_path)
  #       end
  #     end
  #
  #     describe "with invalid params" do
  #       it "assigns the task_template as @task_template" do
  #         task_template = TaskTemplate.create! valid_attributes
  #         put :update, {:id => task_template.to_param, :task_template => invalid_attributes}, valid_session
  #         expect(assigns(:task_template)).to eq(task_template)
  #       end
  #
  #       it "re-renders the 'edit' template" do
  #         task_template = TaskTemplate.create! valid_attributes
  #         put :update, {:id => task_template.to_param, :task_template => invalid_attributes}, valid_session
  #         expect(response).to render_template("edit")
  #       end
  #     end
  #   end
  #
  #   describe "DELETE destroy" do
  #     it "destroys the requested task_template" do
  #       task_template = TaskTemplate.create! valid_attributes
  #       expect {
  #         delete :destroy, {:id => task_template.to_param}, valid_session
  #       }.to change(TaskTemplate, :count).by(-1)
  #     end
  #
  #     it "redirects to the task_templates list" do
  #       task_template = TaskTemplate.create! valid_attributes
  #       delete :destroy, {:id => task_template.to_param}, valid_session
  #       expect(response).to redirect_to(task_templates_url)
  #     end
  #   end
  #
  # end

  context "As a child" do
    before(:each) do
      @member = FactoryGirl.create(:member, parent: false)
      sign_in_member(@member)
    end

    describe "GET index" do
      it "assigns all task_templates as @task_templates" do
        task_template = FactoryGirl.create(:task_template)
        get :index, {}, valid_session
        expect(response.status).to eq(302)
        expect(flash[:error]).to be_present
      end
    end

    describe "GET show" do
      it "assigns the requested task_template as @task_template" do
        task_template = TaskTemplate.create! valid_attributes
        get :show, {:id => task_template.to_param}, valid_session
        expect(response.status).to eq(302)
        expect(flash[:error]).to be_present
      end
    end

    describe "GET new" do
      it "does not allow new" do
        get :new, {}, valid_session
        expect(response.status).to eq(302)
        expect(flash[:error]).to be_present
      end
    end

    describe "GET edit" do
      it "does not allow edit" do
        task_template = TaskTemplate.create! valid_attributes
        get :edit, {:id => task_template.to_param}, valid_session
        expect(response.status).to eq(302)
        expect(flash[:error]).to be_present
      end
    end

    describe "POST create" do
      it "does not allow create" do
        post :create, {:task_template => valid_attributes}, valid_session
        expect(response.status).to eq(302)
        expect(flash[:error]).to be_present
      end
    end

    describe "PUT update" do
      it "does not allow update" do
        task_template = TaskTemplate.create! valid_attributes
        put :update, {:id => task_template.to_param, :task_template => valid_attributes}, valid_session
        expect(response.status).to eq(302)
        expect(flash[:error]).to be_present
      end
    end

    describe "DELETE destroy" do
      it "does not allow delete" do
        task_template = TaskTemplate.create! valid_attributes
        delete :destroy, {:id => task_template.to_param, :task_template => valid_attributes}, valid_session
        expect(response.status).to eq(302)
        expect(flash[:error]).to be_present
      end
    end
  end

  context "As a parent" do
    before(:each) do
      @user = FactoryGirl.create(:user, admin: false)
      sign_in(@user)
    end

    describe "GET index" do
      it "assigns all task_templates as @task_templates" do
        task_template = FactoryGirl.create(:task_template)
        get :index, {}, valid_session
        expect(assigns(:task_templates)).to match_array(TaskTemplate.all)
      end
    end

    describe "GET show" do
      it "assigns the requested task_template as @task_template" do
        task_template = TaskTemplate.create! valid_attributes
        get :show, {:id => task_template.to_param}, valid_session
        expect(assigns(:task_template)).to eq(task_template)
      end
    end

    describe "GET new" do
      it "does not allow new" do
        get :new, {}, valid_session
        expect(response.status).to eq(302)
        expect(flash[:error]).to be_present
      end
    end

    describe "GET edit" do
      it "does not allow edit" do
        task_template = TaskTemplate.create! valid_attributes
        get :edit, {:id => task_template.to_param}, valid_session
        expect(response.status).to eq(302)
        expect(flash[:error]).to be_present
      end
    end

    describe "POST create" do
      it "does not allow create" do
        post :create, {:task_template => valid_attributes}, valid_session
        expect(response.status).to eq(302)
        expect(flash[:error]).to be_present
      end
    end

    describe "PUT update" do
      it "does not allow update" do
        task_template = TaskTemplate.create! valid_attributes
        put :update, {:id => task_template.to_param, :task_template => valid_attributes}, valid_session
        expect(response.status).to eq(302)
        expect(flash[:error]).to be_present
      end
    end

    describe "DELETE destroy" do
      it "does not allow delete" do
        task_template = TaskTemplate.create! valid_attributes
        delete :destroy, {:id => task_template.to_param, :task_template => valid_attributes}, valid_session
        expect(response.status).to eq(302)
        expect(flash[:error]).to be_present
      end
    end
  end

end
